import { Schema } from "effect";

/** List of properties that might hold substrings for translation (not 100% coverage, might be updated) */
export const StringsFileProperties = Schema.Literal(
  "agility",
  "agility_hilight",
  "awakentip",
  "bonus_defense_fixed",
  "bonus_hpregen",
  "bonus_manaregen",
  "bufftip",
  "buffubertip",
  "colon_agility",
  "colon_gold",
  "colon_gold_income_rate",
  "colon_intellect",
  "colon_lumber",
  "colon_lumber_income_rate",
  "colon_strength",
  "description",
  "gold",
  "goldandlumberfromally",
  "goldfromally",
  "intellect",
  "intellect_hilight",
  "intelligence",
  "lumber",
  "lumberfromally",
  "name",
  "nogold",
  "nolumber",
  "propernames",
  "researchtip",
  "researchubertip",
  "resource_ubertip_gold",
  "resource_ubertip_lumber",
  "revivetip",
  "strength",
  "strength_hilight",
  "tip",
  "ubertip",
  "untip",
  "unubertip",
  "upkeep_high",
  "upkeep_low",
  "upkeep_none",
);
export type StringsFileProperties = typeof StringsFileProperties.Type;
