name: publish
on:
  push:
    branches: prod

permissions:
  id-token: write
  contents: read

jobs:
  build:
    environment: npm
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [24]

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Publishing
        run: pnpm run publish-package
