name: publish

on:
  workflow_run:
    workflows: [release]
    types: [completed]

permissions:
  id-token: write
  contents: read

jobs:
  on-success:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Pack the library
        run: pnpm pack

      - name: Publish to npm
        run: |
          pnpm publish ./*.tgz \
            --access public \
            --provenance
